# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/homeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1017, 543)
        HomeWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setStyleSheet("background: url(C:\\Users\\faisa\\Desktop\\ENG22\\2nd\\EE495\\encryption_app\\assets\\images\\background2.jpg) no-repeat center center;")
        self.centralwidget.setObjectName("centralwidget")
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
